### ISSUE TITLE
WhatsApp Buttons

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [open-wa/wa-automate-nodejs#98] opened 2020-02-05 23:20 UTC
![image](https://user-images.githubusercontent.com/1152426/73892179-f13d4a80-4854-11ea-80b3-8723d7df3290.png)

**Comment by joaomirandasa** [comment] 2020-02-05 23:26
**Woow**! We can create amazing things with this kind of messages, someone knows how to implement?! 
Following this issue! Up Up

**Comment by smashah** [comment] 2020-02-06 01:10
oh my word
 I always knew there was a button type. Never seen it in the wild though.

**Comment by smashah** [comment] 2020-02-06 01:20
might need to skype call/remote desktop one of you to reverse engineer this one.

**Comment by joaomirandasa** [comment] 2020-02-06 01:22
@smashah Awesome! i'm excited to initiate an reverse engineer on this one - i will send you an private message to discuss better

**Comment by joaomirandasa** [comment] 2020-02-06 01:25
> might need to skype call/remote desktop one of you to reverse engineer this one.

Meet-me at Telegram to better discuss: https://t.me/liveapps

**Comment by smashah** [comment] 2020-02-06 01:35
Join discord:

https://discord.gg/uk5mbn

**Comment by smashah** [comment] 2020-02-06 01:48
@andersondeoliveiramachado @joaomirandasa let me know once you've joined my tag is @ shah

**Comment by joaomirandasa** [comment] 2020-02-06 02:56
Degug information about new message type:

[template_button.txt](https://github.com/smashah/sulla/files/4162985/template_button.txt)

**Comment by smashah** [comment] 2020-02-06 03:28
thanks @joaomirandasa 

The questions are of type template. They can also have subtypes (i.e the body of the questions). Also the buttons themselves have subtypes (i.e the action performed in response to the question) as seen below in the WhatsApp app code.

![image](https://user-images.githubusercontent.com/5903821/73903245-6712d780-4890-11ea-87db-a802b30de9e2.png)


This means that you can send a user a picture and then show a button to start a call. Wild stuff.

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 13:35
https://wa.me/5511955705173?text=Ol%C3%A1,%20UAM!

this is the college whatsapp link that has this business account with this button feature.

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 13:42
![image](https://user-images.githubusercontent.com/1152426/73942135-4d43b580-48cd-11ea-9135-907a352109bb.png)

**Comment by smashah** [comment] 2020-02-06 14:29
I've managed to construct this message properly however, unfortunately, the message gets 'dropped'.

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 14:37
> I've managed to construct this message properly however, unfortunately, the message gets 'dropped'.

most likely to have validation by account type. This account is a business account.

**Comment by joaomirandasa** [comment] 2020-02-06 15:30
@smashah Could you give me more information about the drop? witch kind of account did you used to test, an Business or personal account? 

Probably this just can be sent from WBusiness and searching aboout informations of that previous number we realize it's not an verified account - so probably they are using an 3rd party solution provided by someone else, at this moment me and @andersondeoliveiramachado 
are searching more possible informations about provider of api solution used for them

**Comment by smashah** [comment] 2020-02-06 16:00
I fixed the drop. It doesn't come out the other end with the buttons though.

**Comment by marcelocecin** [comment] 2020-02-06 17:09
https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates/
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/media-message-templates/
https://developers.facebook.com/docs/whatsapp/message-templates/
https://developers.facebook.com/docs/whatsapp/message-templates/guidelines/
https://developers.facebook.com/docs/whatsapp/message-templates/creation/
https://developers.facebook.com/docs/whatsapp/message-templates/sending/

**Comment by smashah** [comment] 2020-02-06 19:46
This is the blocker:

![image](https://user-images.githubusercontent.com/5903821/73971923-bd772900-4917-11ea-8171-a93389b27e1c.png)

If it detects that you're trying to send a template with a `subtype:text` then it converts it to a `type:chat` then parses it again. I believe that if this can be bypassed then the buttons would go through properly.

**Comment by smashah** [comment] 2020-02-06 20:00
@andersondeoliveiramachado @joaomirandasa @marcelocecin have a play around in the chrome console.

https://github.com/smashah/sulla/blob/a9b94acd08ca4067f13eb0bd926ce1d257b7bdcc/src/lib/wapi.js#L1689

I can't get this to work 🤷

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 20:05
Is it possible to test with any type of account?

**Comment by smashah** [comment] 2020-02-06 20:14
I've tested with both business and personal and it changes into a normal chat during sending. Doesn't work on either as expected. The only thing left to do is to mutate the app code somehow. I don't know how to do that

**Comment by marcelocecin** [comment] 2020-02-06 20:17
I believe that it is not possible to send this type of message via whatsapp web, only via official API

**Comment by marcelocecin** [comment] 2020-02-06 20:22
@andersondeoliveiramachado could you try to share the message with another number on whatsapp web and attach the prints?

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 20:22
![image](https://user-images.githubusercontent.com/1152426/73975439-15586480-4905-11ea-91d8-55220fc5d7e1.png)
![image](https://user-images.githubusercontent.com/1152426/73975536-4df83e00-4905-11ea-86ec-41d2312ddc1e.png)

**Comment by joaomirandasa** [comment] 2020-02-06 20:32
I tried to share message with another number, buttons simply disapear! i don't know why but isn't work as expected. 

![Captura de Tela 2020-02-06 às 17 24 54](https://user-images.githubusercontent.com/29043431/73975696-a29bb900-4905-11ea-9b41-444f5145eace.png)

**Comment by andersondeoliveiramachado** [comment] 2020-02-06 20:42
> could you try to share the message with another number on whatsapp web and attach the prints?

Yes , what is the number?

**Comment by smashah** [comment] 2020-02-07 02:50
tiny update

![image](https://user-images.githubusercontent.com/5903821/73996815-9d198f80-4954-11ea-8351-f6f18884d852.png)

**Comment by smashah** [comment] 2020-02-07 04:37
try this in the browser:

https://github.com/smashah/sulla/blob/82ee145b9d83222aa506ff3bfc72a9aacd9164da/src/lib/wapi.js#L1692

I think this is as close as i'm gonna get for now.

**Comment by Douglas12ds** [comment] 2020-02-07 05:08
Wow! Sulla is envolver faster than i thought. Great to see this. Soon I'll test the button's features.

Also... Looks like brazilian people loves Sulla. I have never seen an non-brazilian repository with so many brazilians interacting. 

_Beijos do Brasil!_

**Comment by joaomirandasa** [comment] 2020-02-07 05:10
Thanks Sulla for so engagement on discover and reproduce this features! Amazing to see this project growing every day.

Regards from Brazil! Come here to drink a beer!

**Comment by marcelocecin** [comment] 2020-02-07 09:56
<img width="834" alt="original" src="https://user-images.githubusercontent.com/2955762/74019595-aae00c80-4976-11ea-8ed3-d330630e61ae.png">

I believe that it is not possible to send this type of message via whatsapp web, only via official API
when I try to forward to another contact, only the text is forwarded and not the buttons

<img width="843" alt="fw" src="https://user-images.githubusercontent.com/2955762/74019628-b7fcfb80-4976-11ea-8b04-cf89c32166d0.png">

**Comment by arturromaorocha** [comment] 2020-02-07 20:05
Boa tarde, como implemento isso? devo chamar o  'sendButtons2' com algum parâmetro? 

Good afternoon, how do I implement this? should I call 'sendButtons2' with any parameters?

**Comment by andersondeoliveiramachado** [comment] 2020-02-08 20:23
> Boa tarde, como implemento isso? devo chamar o 'sendButtons2' com algum parâmetro?

No momento a função ainda não funciona ( Botões não chegam ao destino ) . Você pode fazer uma chamada utilizando sendButtons2 para ver os botões no web browser do remetente.
 
> Good afternoon, how do I implement this? should I call 'sendButtons2' with any parameters?

At the moment the function still does not work (Buttons do not reach the destination). You can make a call using sendButtons2 to see the buttons on the sender's web browser.

Comment Line : 

       //comment the next line to see the buttons. the next line will send the message but whatsapp wil sanitize it of all the buttony goodness
        return Store.sendMsgRecord(t)

**Comment by smashah** [comment] 2020-02-08 20:32
thanks @andersondeoliveiramachado 

The next thing to try is setting up an instance of sulla-hotfix on the receivers phone with onAnMessage listener and seeing if it actually receives the message with the correct type (template).

**Comment by andersondeoliveiramachado** [comment] 2020-02-08 20:49
> The next thing to try is setting up an instance of sulla-hotfix on the receivers phone with onAnMessage listener and seeing if it actually receives the message with the correct type (template).

very good idea, so you can clear a doubt if the message is being modified after sending.

**Comment by andersondeoliveiramachado** [comment] 2020-02-08 21:20
with the active line return Store.sendMsgRecord(t), I get a message at the destination like this:

![image](https://user-images.githubusercontent.com/1152426/74092201-9186af80-4a9f-11ea-80e5-9cc27b7dd246.png)

**Comment by smashah** [comment] 2020-02-10 21:34
@andersondeoliveiramachado @joaomirandasa @marcelocecin @Douglas12ds Some progress.

You can run `WAPI.sendButtons2(chatId)` and it will 'send' the message over the server however it will end up in your sender phone as if it came from the recipient.

I tried to debug the issue. This is happening because the sender phone is mutating the message payload and setting `fromMe:false` in the message object id attribute. With this annoying little change, it results in the button message never being sent to the recipient. A possible remedy for this would be to use the oldest possible version of whatsapp apk and install it onto the sender phone.

Anyways. have fun!

P.S I've spent an ungodly amount of time trying to work this out and if you're having fun using sulla-hotfix or get some good use out of it I'd super appreciate some support on my [BMAC](https://www.buymeacoffee.com/smashah). Thanks

**Comment by Douglas12ds** [comment] 2020-02-27 01:54
Hi there. Any updates?

**Comment by smashah** [comment] 2020-02-28 07:58
@Douglas12ds nope. Next thing to do would be to hack whatsapp apk.

**Comment by andersondeoliveiramachado** [comment] 2020-02-28 13:46
https://ibotpeaches.github.io/Apktool/
@smashah  would it be something like using a tool like that?

**Comment by tinyCoder32** [comment] 2020-03-31 23:37
Is there any update on this please? both sending buttons functions are not sending the message, it shows as "pending" and never sends like there is an error.

**Comment by smashah** [comment] 2020-04-01 00:40
@tinyCoder32 this issue is stale and will probably never be implemented.

**Comment by m7mdcc** [comment] 2020-04-18 17:01
Hmmm , as mentioned above its implemented in Whatsapp Business API only .  
It's amazing feature , Sadly we cant do that here :( . Telegram API have this by the way .

**Comment by smashah** [comment] 2020-04-21 22:32
It's clear that facebook values the ability to protect these buttons more than they value message integrity. Since there's no way around this, for now, I will be closing this issue but leaving it pinned.

**Comment by joaomirandasa** [comment] 2020-04-28 15:19
To whom It May Concern:
I bring news and updates on the use of the buttons, I fear that we will never be able to use this feature without official authorization from WhatsApp. The process for using the buttons in a conversation requires prior approval by WhatsApp on the type of button and content you want to use. Allowing the application of this in the conversation only after its prior authorization.

The process for using the buttons in the official API works as follows:
1º) Declare the content of the message body.
2) Declare the nature of the buttons you want to use (link, phone, quick response)
3) fill in the content of all fields, using only a few context variables if necessary - to make the use dynamic.
4) When all this is done, the button template must be sent for approval.
5) If approved, you will have a template message code to use.
6) To use in the conversation, you must send the button template ID as a request parameter.

Thinking intelligently, we will never be able to use this because we will never be able to get this ID of the template message (THAT HERE WE AFFIRM, IS VALIDATED BY THE PHONE AT THE MESSAGE SENDING MESSAGE). I therefore suggest the solution of this ISSUE to prevent future users from being interested in a dead-end solution. If you want to use it, start the approval process for the official API.

NOTE: I highlight that it does not make much difference in the conversation since you can not use the buttons when you want and with the content you want, only at the points of the conversation previously stated.

@smashah please close this issue for don't mistakes in future.

**Comment by ImBIOS** [comment] 2020-07-13 23:43
is this really closed? how to make an awesome button like that?

**Comment by smashah** [comment] 2021-07-14 17:03
Bruh

**Comment by smashah** [comment] 2021-07-14 17:09
![Screenshot_20210714-175255](https://user-images.githubusercontent.com/5903821/125663706-94c9308a-9791-4b10-a5e0-df25250033cd.jpg)

**Comment by ImBIOS** [comment] 2021-07-15 13:45
how to approach this? @smashah

**Comment by smashah** [comment] 2021-07-15 14:43
@ImBIOS with excitement.

Keep an eye on this issue. This feature will be releasing soon

**Comment by smashah** [comment] 2021-07-15 22:00
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment] 2021-07-15 22:02
# Changelog

## 🚀 Release [4.11.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.10.0...4.11.0) (2021-07-15)

- Release 4.11.0 [`e09237a`](https://github.com/open-wa/wa-automate-nodejs/commit/e09237a8a410d5d0774bca6efc81398f3051fa8b)
- 📝  docs fix [`a36a702`](https://github.com/open-wa/wa-automate-nodejs/commit/a36a70262579b3243c5a0e10488f677da8a42e55)
- ✨ feat [INSIDERS]: `sendListMessage` #1903 [`106a43d`](https://github.com/open-wa/wa-automate-nodejs/commit/106a43d78261f04c26fc0a08f2a5ec5b78255038)
- ✨ feat: `sendButtons` #98 [`c075eee`](https://github.com/open-wa/wa-automate-nodejs/commit/c075eee3aa6eb52282be6ce1edc4214b73a6672b)
- ✨ feat: `sendBanner` #1793 [`7398172`](https://github.com/open-wa/wa-automate-nodejs/commit/7398172563cef0f7476386324e99e15acd1c3155)
- 🥚  patches update [`cdbf6c3`](https://github.com/open-wa/wa-automate-nodejs/commit/cdbf6c3a9918630b15d90e592e50c70227949a90)

**Comment by smashah** [comment] 2021-07-15 22:06
It took 1.5 years but finally, it's here. I'm proud to announce you can finally send simple button messages with open-wa (limit is 3 buttons)

```javascript
await client.sendButtons(cid, "Body", [
        {
            id: "1",
            "text": "Click"
        },
        {
            id: "1",
            "text": "Call"
        },
        {
            id: "1",
            "text": "Open Link"
        }
    ], "title", "footer")
```

result:

![image](https://user-images.githubusercontent.com/5903821/125863776-c6ae640b-5ef2-4253-95b7-0127e8b8f380.png)

@andersondeoliveiramachado @tinyCoder32 @m7mdcc @joaomirandasa 

closing. thanks

**Closed by smashah** 2021-07-15 22:06 UTC
Labels: Requires Investigation, enhancement

**Comment by m7mdcc** [comment] 2021-07-22 15:06
Salam @smashah  , Great Job .. 3 buttons is limit ? could we send more ? finaly YOU DID IT HEHEHE

**Comment by smashah** [comment] 2021-07-22 17:13
Ws @m7mdcc I tried with 4 and more but it only ever showed three. That's the limit from wa

**Comment by mrbarnk** [comment] 2021-07-28 17:40
> tiny update
> 
> ![image](https://user-images.githubusercontent.com/5903821/73996815-9d198f80-4954-11ea-8351-f6f18884d852.png)

How can I style the buttons like this? The icon and the arrangement.

**Comment by smashah** [comment] 2021-07-28 18:08
@mrbarnk these are special buttons (url & call). They are still not available for use outside the official API.

I tested these types of buttons recently before releasing normal buttons for the library and it still comes up in the chat as if it was sent by the recipient.

I doubt we'll ever get access to these special buttons.

**Comment by mrbarnk** [comment] 2021-07-28 20:07
Oh! Well, Kudos on this normal button alone.

**Comment by sparrow-code** [comment] 2022-07-11 20:25
> It took 1.5 years but finally, it's here. I'm proud to announce you can finally send simple button messages with open-wa (limit is 3 buttons)
> 
> ```js
> await client.sendButtons(chatId, "Body", [
>         {
>             id: "1",
>             "text": "Click"
>         },
>         {
>             id: "1",
>             "text": "Call"
>         },
>         {
>             id: "1",
>             "text": "Open Link"
>         }
>     ], "title", "footer")
> ```
> 
> result:
> 
> ![image](https://user-images.githubusercontent.com/5903821/125863776-c6ae640b-5ef2-4253-95b7-0127e8b8f380.png)
> 
> @andersondeoliveiramachado @tinyCoder32 @m7mdcc @joaomirandasa
> 
> closing. thanks

But This Command And Function dosn't giving response and nor showing any error

**Comment by smashah** [comment] 2022-07-13 14:17
@sparrow-code it is working fine here. Log the output of that command it to check if it returns a message id.

**Comment by ivenkatraj** [comment] 2022-08-23 05:50
@smashah I read the isues. But how how create the whatsapp button with the program you mentioned [here](https://github.com/open-wa/wa-automate-nodejs/issues/98#issuecomment-881042026) please please explain step by step process. I don't know how tho run this. Would be bery much happy if you could explain this. Please.
