### ISSUE TITLE
Send mp3 as a document

### ISSUE THREAD

**Issue by zalviandyr** [open-wa/wa-automate-nodejs#1127] opened 2020-12-01 08:30 UTC
How can i send a mp3 file as document ?
i have tried function sendFile and sendFileFromURL with argument ptt set to false, but still send audio like ptt not as a document

**Comment by smashah** [comment] 2020-12-01 16:08
Duplicate of #1039 

Coming soon

**Closed by smashah** 2020-12-01 16:08 UTC
