### ISSUE TITLE
sendButton to group chat no work in MD session

### ISSUE THREAD

**Issue by eehome** [open-wa/wa-automate-nodejs#2521] opened 2022-02-22 03:17 UTC
Buttons are not sent to group chat in MD mode.
In single it works fine.

Error - (node:9949) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: asUserWid: wid is not a user wid

Sending to private chats works correctly (Valid License: Insider Program). In single session, buttons are correctly sent to private and to a group.

**Comment by smashah** [comment] 2022-02-22 10:26
@eehome I'll check what's going on

**Comment by t0g3pii** [comment] 2022-02-25 12:51
Can't reproduce this on my side.
For me its working on MD in Chats & Groups without Problems.
Either no Problems in Single Session nor Multi Session.
(Newest Version & Insider License)

**Comment by suzuya1331** [comment] 2022-02-25 12:59
> 

I have Newest Version & Insider License and having this issue for buttons and listmessages

**Comment by suzuya1331** [comment] 2022-02-25 13:02
![image](https://user-images.githubusercontent.com/60817875/155719640-21fb3853-ef91-4eae-8cd6-e491dc29b0fa.png)

**Comment by dandyraka** [comment] 2022-02-25 18:38
Same here, only work on private chat.
Version: 4.31.7 

![image](https://user-images.githubusercontent.com/18587059/155769462-18e17463-6c6c-41c2-92ef-eb2042e03413.png)

**Comment by smashah** [comment] 2022-02-25 18:41
It's being worked on, please hold.

**Comment by smashah** [comment] 2022-04-04 02:54
@dandyraka @eehome @suzuya1331 this is fixed now please restart your process and try again.

thanks for your patience

**Closed by smashah** 2022-04-04 02:54 UTC
