### ISSUE TITLE
QR Not authenticating and bug message

### ISSUE THREAD

**Issue by randracar** [open-wa/wa-automate-nodejs#1168] opened 2020-12-11 00:25 UTC
**Describe the bug**
When trying to authenticate, an error message appears, and the QR code appears after. But, the QR code does not work, and does not authenticate.
**Steps to Reproduce**
I could not find an way to reproduce it.

**create() code**
This is the code you use to create the client. e.g
```javascript
const options = {
    sessionId: 'Imperial',
    headless: true,
    qrTimeout: 0,
    authTimeout: 0,
    restartOnCrash: start,
    cacheEnabled: false,
    useChrome: true,
    killProcessOnBrowserClose: true,
    throwErrorOnTosBlock: false,
    chromiumArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--aggressive-cache-discard',
        '--disable-cache',
        '--disable-application-cache',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0'
    ]
}

create(options)
    .then((client) => start(client))
    .catch((err) => new Error(err))
```

**Expected behavior**
I expected it to authenticate normally.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
set -> e Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at window.<computed>.window.<computed> (/home/random-guy/.npm/_npx/6213/lib/node_modules/@open-wa/wa-automate/dist/lib/launch.js:1:36887)
    at __puppeteer_evaluation_script__:3:89
    at ExecutionContext._evaluateInternal (/home/random-guy/.npm/_npx/6213/lib/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
Happens every time.

**Comment by smashah** [comment] 2020-12-11 11:19
@randracar thanks for filling out the issue template, there is some information printed after the logo in the logs. can you add that here please, and actually include all the logs from the process. The system is also meant to take some screenshots. Please add those screenshots also.

thanks

**Comment by randracar** [comment] 2020-12-11 16:02
@smashah , this is everything that appears.

The following appears on the logs folder:

![1607702016583](https://user-images.githubusercontent.com/63797127/101925164-5322bb00-3bb0-11eb-9e57-a833b767d807.jpg)

This is what appears on the terminal.

![Captura de tela de 2020-12-11 12-55-54](https://user-images.githubusercontent.com/63797127/101925253-6b92d580-3bb0-11eb-8bf2-3434688b6b17.png)
![Captura de tela de 2020-12-11 12-59-03](https://user-images.githubusercontent.com/63797127/101925483-abf25380-3bb0-11eb-8c87-d1eeed091d39.png)

**Comment by smashah** [comment] 2020-12-11 17:06
duplicate: #1117

https://github.com/open-wa/wa-automate-nodejs/issues/1117#issuecomment-739096385

**Comment by randracar** [comment] 2020-12-12 17:46
@smashah I did what you said on how to resolve it, but it did not work. Same error message, same everything.

**Comment by smashah** [comment] 2020-12-12 17:49
@randracar can you try without all of those chrome options please

**Comment by randracar** [comment] 2020-12-12 17:52
@smashah Same error.




![Captura de tela de 2020-12-12 14-51-11](https://user-images.githubusercontent.com/63797127/101991147-956bfb00-3c89-11eb-9dbe-56723ae9b241.png)

**Comment by smashah** [comment] 2020-12-12 18:04
@randracar I will work on this tonight

**Comment by randracar** [comment] 2020-12-12 18:04
@smashah Ok, thank you for your time helping me.

**Comment by JulioLongo** [comment] 2020-12-12 23:08
Same problem here

**Comment by NasirKhalid24** [comment] 2020-12-13 19:41
Running on ParrotOS linux and having the same issue - it started recently. Initially I would just keep re-starting the server and it would work eventually but now the issue is persistent

**Comment by smashah** [comment] 2020-12-13 19:48
@NasirKhalid24 will be releasing a new version in a few minuets. stand by

**Comment by smashah** [comment] 2020-12-13 21:53
@NasirKhalid24 @JulioLongo @randracar Can you please try the latest version:

https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.9

and report back if this issue has been resolved.

Thanks

**Comment by NasirKhalid24** [comment] 2020-12-13 23:18
> @NasirKhalid24 @JulioLongo @randracar Can you please try the latest version:
> 
> https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.9
> 
> and report back if this issue has been resolved.
> 
> Thanks

No longer having this issue - back to normal in the latest build. Thanks!

**Comment by smashah** [comment] 2020-12-14 13:46
Closing thanks

**Closed** 2020-12-14 13:46 UTC
