### ISSUE TITLE
client.sendAudio returns a non native WhatsApp audio

### ISSUE THREAD

**Issue by urielexis64** [open-wa/wa-automate-nodejs#1732] opened 2021-05-27 15:29 UTC
**Describe the bug**
When use the new feature "send audio as native WhatsApp audio" it returns a mp3 file that cannot play in the app. ()it's the same when use **client.sendFile(...)**

**Steps to Reproduce**
1. Just using the function **client.sendAudio(from, "audio.mp3", id);**

**Expected behavior**
Anative WhatsApp audio with the ability to be played in the application without the need to resort to external applications.

**Screenshots**
I expect this: 
<img width="50%" src="https://user-images.githubusercontent.com/47485144/119853813-c190d680-becd-11eb-9b1e-8df44fc7b68e.jpg"/>

I got this: 
<img width="50%" src="https://user-images.githubusercontent.com/47485144/119853863-cbb2d500-becd-11eb-9d49-fb2978af8ee5.jpg"/>

**Host (please complete the following information):**
 - OS: Android 
 - WhatsApp Version: 2.21.10.16
 - @open-wa/wa-automate version: 4.1.0

**Comment by smashah** [comment] 2021-05-27 15:39
@urielexis64 in the first example you did not quote another message. this seems to be a limitation of WA itself and the only thing I can do about it is to remove the 3rd parameter.

Please try again with:

```
client.sendAudio(from, "audio.mp3");
```

**Comment by urielexis64** [comment] 2021-05-27 16:26
@smashah I tried and it still doesn't work :(
but thanks for the response :)

**Comment by smashah** [comment] 2021-05-27 16:38
@urielexis64 there is something wrong with how the audio file is being referenced. You should log the result from the ytdl and try to explicitly set the URL of the audio file.

For example, this should work (it is what i am using for testing):

```javascript
  await client.sendAudio(from, 'https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3')
```

**Comment by smashah** [comment] 2021-05-30 13:37
I tried the above code again today and it seems to be functioning as intended.

Closing.

Thanks

**Closed by smashah** 2021-05-30 13:37 UTC
