### ISSUE TITLE
sendLinkWithAutoPreview does not show Auto-Preview

### ISSUE THREAD

**Issue by Kuroosh** [open-wa/wa-automate-nodejs#2603] opened 2022-03-28 13:55 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

it worked before i updated the module...
now its just sending it as a text without auto-preview.

### Expected Behavior

it should show the auto-preview lmao

### Steps To Reproduce

just try to use `sendLinkWithAutoPreview` with a link.. it will not work.

### create() code

```markdown
await VenoX.sendLinkWithAutoPreview(groupid, previewLink, '\nTEST-CODE');
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2210.9",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.7 UPDATE AVAILABLE: 4.32.17",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.0",
  "OS": "Windows Server 2019",
  "START_TS": 1648475739393
}
```

### Environment

```markdown
- OS: Windows Server 2019
- Node: v16.13.2
- npm: npm@8.1.2
```

**Comment by t0g3pii** [comment] 2022-03-28 13:57
![Uploading Screenshot_20220328-153322_WhatsApp.jpg…]()

Can Approve that Issue

**Comment by t0g3pii** [comment] 2022-03-28 16:21
Duplicate of #2545
Reason: Issue from wa itself with Multi-Device

**Comment by Kuroosh** [comment] 2022-03-28 21:33
btw i tried it without multi-device... it didn't worked too...

**Comment by smashah** [comment] 2022-03-29 02:19
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment] 2022-03-29 02:22
# Changelog

## 🚀 Release [4.33.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.32.17...4.33.0) (2022-03-29)

- 🥚 patches update. fixes #2587 [`#2587`](https://github.com/open-wa/wa-automate-nodejs/issues/2587)
- Release 4.33.0 [`39eec92`](https://github.com/open-wa/wa-automate-nodejs/commit/39eec92506cdcc68b5d5c376cfba8e8600032162)
- ✨ FIX: `sendLinkWithAutoPreview` now working on `MD` #2603 [`7ee118f`](https://github.com/open-wa/wa-automate-nodejs/commit/7ee118f11324ed14eaa31ff6444f5af3c959abfe)
- 🔧 config: added `linkParser` #2603 [`a30b3cd`](https://github.com/open-wa/wa-automate-nodejs/commit/a30b3cd4b599dbd6e946172f80a888787a98fea2)
- 🥚 patches update [`438a6cc`](https://github.com/open-wa/wa-automate-nodejs/commit/438a6cc37e9f610c15e5c6e8798ef927a50fe9f2)
- 🥚 patches update [`af37621`](https://github.com/open-wa/wa-automate-nodejs/commit/af376212ae946a2d909d9e70a95fc985d2d9ce20)
- updated types-only package [`6748d13`](https://github.com/open-wa/wa-automate-nodejs/commit/6748d135cfc00f82aeaac4785257193a1007041d)

**Comment by smashah** [comment] 2022-03-29 02:24
fixed in latest version

**Comment by smashah** [comment] 2022-03-29 02:43
The workaround for this was to get the meta tags outside the browser context and then construct the link message manually. Instead of integrating another dependency for something that most people might not need, I decided to deploy a new api (on me) which grabs the link preview details. 

You can choose to [deploy your own](https://github.com/RemiixInc/meta-grabber-serverless) (which I would prefer you do to save me some money) via [`Config.linkParser`](https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html#linkParser)

https://github.com/RemiixInc/meta-grabber-serverless

**Closed** 2022-03-29 02:49 UTC
