### ISSUE TITLE
Files stop sending after very large volume of messages

### ISSUE THREAD

**Issue by JuanMontero0525** [open-wa/wa-automate-nodejs#1737] opened 2021-05-29 15:56 UTC
**Describe the bug**
Files stop sending after very large volume of messages, only file sending stops but text messages work fine.

I do not know if the browser saves some kind of cache and in a certain time with a large volume of messages the files stop being sent.

**create() code**
```javascript
create({
  sessionId: "COVID_HELPER",
  authTimeout: 60,
  blockCrashLogs: true,
  disableSpins: true,
  headless: false,
  logConsole: false,
  popup: true,
  qrTimeout: 0, 
})
.then(async client =>{
  clientActive = client;
  await start(client);
})
.catch(e=>{
  console.log('Error',e.message);
});
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2119.6,
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.7.0 UPDATE AVAILABLE: 4.1.0',
  BROWSER_VERSION: 'Chrome/90.0.4427.0'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/68971444/120075982-8b8c5780-c071-11eb-8417-39e42d0272d0.png)

**Comment by smashah** [comment] 2021-05-30 13:37
@JuanMontero0525 there is not enough information here to resolve this problem. You will need to share the exact code and parameters that lead to that error'ed message.

It is not a function of time, that is a corrupt message. Based on the screenshot, it looks like the corrupt filename is causing the issue but we cannot be sure until you have some reproducible instructions.

Till then I'll close this issue.

thanks

**Closed by smashah** 2021-05-30 13:37 UTC
