### ISSUE TITLE
sendLinkWithAutoPreview endpoint is not sending message

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#2744] opened 2022-06-14 09:06 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

When I send following request, it return response success, but message is not getting sent

`{
  "args": {
    "to": "1211113023324113178@g.us",
    "url": "https://amzn.to/39jZfzw"
  }
}`

### Expected Behavior

it should send message with link preview

### Steps To Reproduce

send message on sendLinkWithAutoPreview  end point from api-docs 

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2220.8",
  "WA_AUTOMATE_VERSION": "4.39.0",
  "BROWSER_VERSION": "HeadlessChrome/102.0.5005.115",
  "START_TS": 1655196612769,
  "RAM_INFO": "Total: 7.81 GB | Free: 6.99 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "a0fd8",
  "LAUNCH_TIME_MS": 40202,
  "ACC_TYPE": "PERSONAL",
  "chats": 500,
  "messages": 667,
  "contacts": 10300,
  "isMd": true,
  "INSTANCE_ID": "6ec51623-406c-45b2-8eca-baaad19e34a2"
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 18.3.0
- npm: 8.11.0
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/12126671/173538943-f9898da2-ec97-4f63-965f-64cd781aa194.png)

**Comment by smashah** [comment] 2022-06-17 16:08
The issue is the fact that amazon does not return expected meta tags

https://www.opengraph.io/use-opengraph-io-scrape-product-details-amazon-com/

**Comment by smashah** [comment] 2022-06-17 16:24
Please track https://github.com/smashah/owa-meta-grabber/issues/1

**Comment by smashah** [comment] 2022-06-17 16:27
@manojsitapara Should be fixed now. Please test and try again.

**Comment by smashah** [comment] 2022-06-17 16:51
Also, you should send a `"text":""` also at least

**Comment by smashah** [comment] 2022-06-17 16:51
tested. working.

**Closed by smashah** 2022-06-17 16:51 UTC

**Comment by manojsitapara** [comment] 2022-06-17 17:45
@smashah I have tried to send message with link as follow, after restarting docker container

> {
>   "args": {
>     "to": "911234567890@c.us",
>     "url": "https://www.amazon.in/United-Colors-Benetton-Shirt-5NS14U008I_Blue/dp/B08MV8P3Z6",
>     "text": "https://amzn.to/3zIIFEa"
>   }
> }

I am getting response success, but not sending message

![image](https://user-images.githubusercontent.com/12126671/174350945-6f7f88bf-64d2-489f-93aa-d4b30bad6b38.png)

**Comment by smashah** [comment] 2022-06-17 17:47
Your text can't be another link. It has to be some other text like a caption and the only link it can include is the original url.

**Comment by manojsitapara** [comment] 2022-06-17 18:01
Yes I did tried that as well, in that case it is keep loading almost more than 4 minutes

![image](https://user-images.githubusercontent.com/12126671/174352896-239ebcc7-9a27-47cf-89ee-cd93dfe2d273.png)

Following is request body

> {
>   "args": {
>     "to": "911234567890@c.us",
>     "url": "https://www.amazon.in/United-Colors-Benetton-Shirt-5NS14U008I_Blue/dp/B08MV8P3Z6",
>     "text": "Test"
>   }
> }

**Comment by manojsitapara** [comment] 2022-06-17 18:21
Following URL return meta data correctly, but some how it is not working for me. I am not sure if I am doing anything wrong.

https://owa-meta-grabber-kappa.vercel.app/api?url=https://amzn.to/3xZs6CC

> {"title":"Buy MacroMan Men's Solid Trunks (RVBMMRTPLDP500 and Print May Vary_95 cm) at Amazon.in","description":"Buy MacroMan Men's Solid Trunks (RVBMMRTPLDP500 and Print May Vary_95 cm) from Trunks at Amazon.in","url":"https://amzn.to/3xZs6CC","site_name":"Amazon","image":"https://images-eu.ssl-images-amazon.com/images/I/71KEAaG581L._SY445_SX342_QL70_ML2_.jpg","icon":"https://www.amazon.com/favicon.ico","success":true}

**Comment by smashah** [comment] 2022-06-17 20:39
why are you removing the `https://` from the request to open-wa????????

You don't need to roll your own link parsing server.

This works:

```js
{
"args": {
"to": "911234567890@c.us",
"url": "https://amazon.in/United-Colors-Benetton-Shirt-5NS14U008I_Blue/dp/B08MV8P3Z6",
"text": "Test"
}
}
```

**Comment by manojsitapara** [comment] 2022-06-18 02:26
I am sorry my bad. It works. Thank you

**Comment by manojsitapara** [comment] 2022-06-18 03:27
@smashah I have observed issue, if there are multiple products on the page, it is not sending messages. I think in such case it should either send link preview message or normal message

for example:

> {
>   "args": {
>     "to": "911234567890@c.us",
>     "url": "https://amzn.to/3HyQ8aQ",
>     "text": "Test"
>   }
> }

**Comment by smashah** [comment] 2022-06-18 04:48
@manojsitapara feel free to give back and contribute a PR to the original meta grabber repo with some logic that would help parse these amazon links. Looking forward to it.

**Comment by manojsitapara** [comment] 2022-06-19 04:11
> ```js
> "args": {
> "to": "911234567890@c.us",
> "url": "https://amazon.in/United-Colors-Benetton-Shirt-5NS14U008I_Blue/dp/B08MV8P3Z6",
> "text": "Test"
> }
> ```

@smashah this looks like again stopped sending link preview with above request.

**Comment by manojsitapara** [comment] 2022-06-19 13:34
> @manojsitapara feel free to give back and contribute a PR to the original meta grabber repo with some logic that would help parse these amazon links. Looking forward to it.

@smashah  When I debug code, it is giving output without any error, however giving error on server

> {
>   title: "Amazon.in",
>   description: null,
>   url: "https://amzn.to/3HyQ8aQ",
>   site_name: "Amazon",
>   image: "https://www.amazon.com/favicon.ico",
>   icon: "https://www.amazon.com/favicon.ico",
>   keywords: undefined,
> }
