### ISSUE TITLE
today enable to send image

### ISSUE THREAD

**Issue by abbassnet** [open-wa/wa-automate-nodejs#1412] opened 2021-02-26 18:13 UTC
when we try to send image from browser system return this error message 
bet yesterdy all is work correctly

Promise {<rejected>: TypeError: mc.processFiles is not a function
    at Object.window.WAPI.procFiles (<anonymous>:1541:…}
__proto__: Promise
[[PromiseState]]: "rejected"
[[PromiseResult]]: TypeError: mc.processFiles is not a function at Object.window.WAPI.procFiles (<anonymous>:1541:14) at <anonymous>:1439:34 at X (https://web.whatsapp.com/bootstrap_qr.513916447b41999e9e9b.js:1:306419) at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.513916447b41999e9e9b.js:1:306000)
message: "mc.processFiles is not a function"
stack: "TypeError: mc.processFiles is not a function↵    at Object.window.WAPI.procFiles (<anonymous>:1541:14)↵    at <anonymous>:1439:34↵    at X (https://web.whatsapp.com/bootstrap_qr.513916447b41999e9e9b.js:1:306419)↵    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.513916447b41999e9e9b.js:1:306000)"
__proto__: Error

**Comment by smashah** [comment] 2021-02-27 11:23
@abbassnet I think this is the solution to your problem:

https://github.com/open-wa/wa-automate-nodejs/issues/1398#issuecomment-785912146

If not then please fill in the issue template so I can reproduce because I am not able to replicate this problem using the library.

Closing for now.

Thanks

**Closed by smashah** 2021-02-27 11:23 UTC
