### ISSUE TITLE
Specify timeout on send methods

### ISSUE THREAD

**Issue by Sp0derDev** [open-wa/wa-automate-nodejs#1152] opened 2020-12-07 21:13 UTC
When device is not connected, send functions doesn't return until it is connected again.
It waits for an infinite amount of time. Is there a way around this?

**Comment by smashah** [comment] 2020-12-07 21:18
@Sp0derDev you might want to try safeMode. It checks the state before making a request to the browser instance

https://docs.openwa.dev/interfaces/configobject.html#safemode

**Comment by Sp0derDev** [comment] 2020-12-08 18:54
I tried it, it still doesn't work most of the time. It keeps trying to send.

**Comment by smashah** [comment] 2020-12-11 12:38
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by Sp0derDev** [comment] 2020-12-11 12:57
Thank you, do you mind helping with implementing a timeout ?

**Comment by smashah** [comment] 2020-12-11 13:09
@Sp0derDev CI server got stuck on the release, going to try fixing then will explain how to do it

**Comment by smashah** [comment] 2020-12-11 13:11
# Changelog

## 🚀 Release [3.1.8](https://github.com/open-wa/wa-automate-nodejs/compare/3.1.7...3.1.8) (2020-12-11)

- build(deps-dev): bump ava from 3.13.0 to 3.14.0 [`#1153`](https://github.com/open-wa/wa-automate-nodejs/pull/1153)
- build(deps-dev): bump husky from 4.3.0 to 4.3.5 [`#1155`](https://github.com/open-wa/wa-automate-nodejs/pull/1155)
- build(deps-dev): bump ts-node from 9.1.0 to 9.1.1 [`#1154`](https://github.com/open-wa/wa-automate-nodejs/pull/1154)
- build(deps): bump cfonts from 2.8.6 to 2.9.0 [`#1156`](https://github.com/open-wa/wa-automate-nodejs/pull/1156)
- build(deps): bump socket.io from 3.0.3 to 3.0.4 [`#1157`](https://github.com/open-wa/wa-automate-nodejs/pull/1157)
- build(deps): bump ini from 1.3.5 to 1.3.7 [`#1174`](https://github.com/open-wa/wa-automate-nodejs/pull/1174)
- build(deps-dev): bump @types/puppeteer from 5.4.1 to 5.4.2 [`#1163`](https://github.com/open-wa/wa-automate-nodejs/pull/1163)
- build(deps): [security] bump ini from 1.3.5 to 1.3.7 [`#1166`](https://github.com/open-wa/wa-automate-nodejs/pull/1166)
- build(deps-dev): bump @types/node from 14.14.10 to 14.14.12 [`#1169`](https://github.com/open-wa/wa-automate-nodejs/pull/1169)
- build(deps): bump swagger-ui-dist from 3.37.2 to 3.38.0 [`#1170`](https://github.com/open-wa/wa-automate-nodejs/pull/1170)
- build(deps-dev): bump marked from 1.2.5 to 1.2.6 [`#1171`](https://github.com/open-wa/wa-automate-nodejs/pull/1171)
- Release 3.1.8 [`034a9a7`](https://github.com/open-wa/wa-automate-nodejs/commit/034a9a7e2968034b725c48ec114eee23aa3c2f4a)
- config: Implemented `callTimeout` #1152 [`1c11b16`](https://github.com/open-wa/wa-automate-nodejs/commit/1c11b16c1cac04dca35c291278239616f74a79f7)
- implemented: `PageEvaluateionTimeout` #1152 [`3a4a9c4`](https://github.com/open-wa/wa-automate-nodejs/commit/3a4a9c4bccfed917609fa3c41a4916ec6952b112)
- chore: Improve `forceRefocus()` documentation [`f6b5ca8`](https://github.com/open-wa/wa-automate-nodejs/commit/f6b5ca8908c46cd7ab1c15b8c3f96ed00382e3f8)
- updated `popup` socket dependency to `3.0.4` [`a8b5f84`](https://github.com/open-wa/wa-automate-nodejs/commit/a8b5f847d5a1a34654f95b33d3b111283e36417d)
- Force update state in safeMode #1152 [`7617277`](https://github.com/open-wa/wa-automate-nodejs/commit/76172779902489928abba13f93ea1fc8ae885625)

**Comment by smashah** [comment] 2020-12-11 14:14
@Sp0derDev Ok. In the latest version (3.1.8) there are two major changes that will help you out.

1. `safeMode` now forces an update to the state of the connection. If it is connected, it will resolve quickly and result in `CONNECTED` and continue with the desired command. If there are issues with the connection between the device and the session then it will resolve in about 6 seconds and throw a confirmed `TIMEOUT` state message (or some other undesirable state).

2. You can now set `callTimeout` in the config ([docs](https://docs.openwa.dev/interfaces/configobject.html#calltimeout)). This is the number of milliseconds the client method will wait before timing out. It will throw a `PageEvaluateionTimeout` error with a generic message. This should free up your process to continue doing other things. Just because you got this error, it does not mean that the desired command failed. It just means your process is no longer waiting for a response so please be careful when using this as some consecutive commands may rely on the resolved value.

I'm sure there will be some teething problems that will need further patches so please report with any feedback/issues. Or just report back if it is working as expected for you so I can close this issue.

Thanks

**Comment by smashah** [comment] 2020-12-13 21:55
Closing for now, please report back if there are any further issues. Thanks

**Closed by smashah** 2020-12-13 21:55 UTC
