### ISSUE TITLE
SendGiphyAsSticker is not working

### ISSUE THREAD

**Issue by Elquemao** [open-wa/wa-automate-nodejs#1912] opened 2021-07-17 15:13 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I'm trying to use that function with a gif uploaded on Giphy by me and it doesn't working.
If I choose another Giphy gif this works.

### Expected Behavior

My gif uploaded on Giphy should be converted into a sticker

### Steps To Reproduce

1. Upload a gif to giphy-
2. use sendGiphyAsSticker() function

### Mode

My own code

### Environment

```markdown
- OS: Windows 10
```

**Comment by smashah** [comment] 2021-07-23 18:09
@Elquemao it sounds like the issue is with your giphy gif.

If you convert it locally to mp4 then send it as a sticker it should work just fine.

Closing due to lack of context and reproduction steps.

**Closed by smashah** 2021-07-23 18:09 UTC
