### ISSUE TITLE
Issue with client.onAck

### ISSUE THREAD

**Issue by priteshpmehta** [open-wa/wa-automate-nodejs#926] opened 2020-10-12 09:04 UTC
**Describe the bug**
If we call **client.onAck** for more than 50 messages, page is being unresponsive and stuck. 

**Steps to Reproduce**
1. call client.onAck((msg:any) => console.log(msg.id.toString(),msg.body,msg.ack)) for more than 50 messages at a time.

**create() code**
This is the code you use to create the client. e.g
```javascript
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onAck((msg:any) => console.log(msg.id.toString(),msg.body,msg.ack));
}
```

**Expected behavior**
It shouldn't stop and return acknowledgement state for all the messages.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2041.6',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.31',
  BROWSER_VERSION: 'HeadlessChrome/86.0.4240.75'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Additional context**
Previously it was returning acknowledge state even more than 500 messages.

**Comment by smashah** [comment] 2020-10-12 17:57
umm what do you mean by `call client.onAck for more than 50 messages at a time` ???

**Comment by priteshpmehta** [comment] 2020-10-12 19:21
Really very sorry, If I am not able to explain you in proper way.

for example, If bot sent 50 messages to any number and after sometime if that number opens/read all the messages then ```client.onAck``` should return acknowledge state as 3 for all 50 messages but it stuck and doesn't continue with any function.

Thanks.

**Comment by smashah** [comment] 2020-10-13 08:42
@priteshpmehta It may not necessarily return 3 for all 50 messages as 3 means that the message has been read (2 blue ticks). This seems like a duplicate of #915 

Please update to the latest version, restart all of your sessions and try again.

**Comment by priteshpmehta** [comment] 2020-10-13 10:14
@smashah I have restarted all the sessions and node process before creating issue here. FYI, I am getting acknowledgement state as 3 (2 blue ticks) for first few chats and then it stops (Read receipts is ON).

**Comment by smashah** [comment] 2020-10-13 10:38
@priteshpmehta I will need more context to recreate this issue. Are you using any other client methods or just `onAck`?

**Comment by priteshpmehta** [comment] 2020-10-13 11:27
Yes, I am using other client methods too.

Here is the sample static code (In actual It is dynamic like text, fileURL, etc.):

```javascript
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    if (message.from === 'xxxxxxx@c.us') {
        for (let index = 0; index < 50; index++) {
            await client.sendText(message.from, '👋 Hello!');
            await client.sendFileFromUrl(message.from, 'https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4', 'video.mp4', 'xxxxx', null, null, true).then((serialized) => {
                console.log(`sendFileFromUrl has serialized ${serialized}\n`);
            }, (err) => {
                console.log(`sendFileFromUrl has error ${err}\n`);
            }); 
        }
    }
  });

  client.onAck((msg) => console.log(msg.id.toString(), msg.ack));
}
```

**Comment by smashah** [comment] 2020-10-14 09:42
@priteshpmehta is it just me (my both phones) or are acknowledgments broken? I can see my own ticks, I can't see a recipient's ticks. :/

**Comment by smashah** [comment] 2020-10-14 09:45
Not just me: https://twitter.com/WABetaInfo/status/1315721552982421507/photo/1

**Comment by priteshpmehta** [comment] 2020-10-15 09:20
> @priteshpmehta is it just me (my both phones) or are acknowledgments broken? I can see my own ticks, I can't see a recipient's ticks. :/

Hi @smashah ,

I guess ```client.onAck()``` is completely broken. I have upgraded @open-wa/wa-automate to 2.1.1 (latest version) and not able to see any acknowledgement.

![image](https://user-images.githubusercontent.com/33055448/96103753-22dcda00-0ee9-11eb-8d72-490f3919c475.png)

**Comment by smashah** [comment] 2020-10-15 09:29
@priteshpmehta as shown in my link above it looks like it's broken from WhatsApps side. I suggest commenting out your `onAck` code for now

**Comment by priteshpmehta** [comment] 2020-10-15 09:51
Sure @smashah .. 
Thanks

**Comment by tadeubarbosa** [comment] 2020-10-15 16:42
I'm with this same problem with onAck method.

**Comment by paulocorcino** [comment] 2020-10-16 08:16
**onAck** to me too not work more. I not saw because before I have been ignoring these messages, but now I need to use to controlling new process.

**Comment by smashah** [comment] 2020-10-16 11:14
@priteshpmehta @paulocorcino can you restart your session, try again and report if the patch worked please. thanks

**Comment by paulocorcino** [comment] 2020-10-16 11:24
![image](https://user-images.githubusercontent.com/7800501/96252670-b6191c80-0f88-11eb-834a-2ea42353a1a9.png)

@smashah Wow! Thank you!

**Closed** 2020-10-16 12:22 UTC
Labels: Awaiting fix confirmation

**Comment by priteshpmehta** [comment] 2020-10-28 07:12
Hi @smashah ,

Just to remind you that the Initial issue in this ticket is still not resolved. Are you able to reproduce it at your end?

**Comment by smashah** [comment] 2020-10-28 07:15
@priteshpmehta this issue is stale now can you make sure your open-wa is updated and if it's still causing problems then please open a new issue thanks
