### ISSUE TITLE
Cannot send message to saved contacts

### ISSUE THREAD

**Issue by faizanjaved5** [open-wa/wa-automate-nodejs#333] opened 2020-04-18 20:42 UTC
Cannot send message tu numbers already saved in contact list and are on whatsapp too

1. Go to 'demo folder'
2. Click on 'index.ts' file
3. Added this line of code

var test= await client.sendText('xxxxx@c.us',"test");
console.log(test);

''xxxxx@c.us'' xxxx is the actual number with country code

4. The returned value in console.log is false..

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
  sessionId:'session1',
  // executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  useChrome: true,
  headless:false,
  throwErrorOnTosBlock:true,
  killTimer:40,
  autoRefresh:true, //default to true
  qrRefreshS:15, //please note that if this is too long then your qr code scan may end up being invalid. Generally qr codes expire every 15 seconds.
  // cacheEnabled:false,
  // devtools:true,
  // blockCrashLogs:true,
  //OR
  // devtools:{
  //   user:'admin',
  //   pass:'root'
  // },
  //example chrome args. THIS MAY BREAK YOUR APP !!!ONLY FOR TESTING FOR NOW!!!.
  // chromiumArgs:[
  //   '--aggressive-cache-discard',
  //   '--disable-cache',
  //   '--disable-application-cache',
  //   '--disable-offline-load-stale-cache',
  //   '--disk-cache-size=0'
  // ]
})
```

**Expected behavior**
a test message should be sent to the number.

```
phone: {
    wa_version: '2.20.44',
    mcc: '410',
    mnc: '003',
    os_version: '9',
    device_manufacturer: '****',
    device_model: 'ginkgo',
    os_build_number: 'PKQ1.190616.001'
  },

```

 - OS: linux

**Comment by smashah** [comment] 2020-04-18 22:13
Duplicate of #254 

If they are in your contacts then start the chat otherwise the process is the exact same as if it's a random stranger's number.

**Closed by smashah** 2020-04-18 22:13 UTC
