### ISSUE TITLE
add custom reply messages

### ISSUE THREAD

**Issue by Jonas33235** [open-wa/wa-automate-nodejs#1349] opened 2021-02-14 22:31 UTC
add custom reply messages like the baileys
example:
    quoted: quotedMessage, 
    contextInfo: { forwardingScore: 2, isForwarded: true }, // some random context info (can show a forwarded message with this too)
    timestamp: Date(), // optional, if you want to manually set the timestamp of the message
    caption: "hello there!", // (for media messages) the caption to send with the media (cannot be sent with stickers though)
    thumbnail: "23GD#4/==", /*

**Comment by smashah** [comment] 2021-02-15 08:03
This is a duplicate of #1198

Nobody has given me a good enough reason to implement this feature that may be abused to put words in people's mouths - so there's little chance this will be implemented.

**Comment by Jonas33235** [comment] 2021-02-15 08:24
I would just use this function to put a message with my number it would be a very useful function that many bot that uses baileys have

**Comment by smashah** [comment] 2021-02-15 15:32
Another library has it therefore this one should also have it? Doesn't sound like a good enough reason to counteract my concerns over abuse. If you'd like to reply to your own messages then I suggest

1. Sending yourself the message, grab the ID
2. Use that ID with `ghostForward` with your comment.

That way your use case of replying to your own non-existent messages are fulfilled and nobody can spoof messages from anyone else

Thanks

**Closed by smashah** 2021-02-15 15:32 UTC
