### ISSUE TITLE
Report BUG !!! TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by osenbal** [open-wa/wa-automate-nodejs#1779] opened 2021-06-13 12:06 UTC
**Describe the bug**
When I run the program, the browser automate close after 30 second.

**Steps to Reproduce**
1. Go to '/node_modules/@open-wa/wa-automate/dist/controllers/browser.js'
3. Scroll down to '== Line 136 =='

**create() code**
This is the code you use to create the client. e.g
```javascript
create( waPage.goto(puppeteer_config_1.puppeteerConfig.WAUrl, {waitUntil: 'networkidle0', timeout: 0}); )
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2121.6,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: 4.4.0,
  BROWSER_VERSION: 88.0.4324.96 (Official Build) (64-bit)
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots.
My Code : [https://pastecode.io/s/shv4jb7wyw](url)
Error  : [https://ibb.co/Y2Wnhm9](url)

**Host (please complete the following information):**
 - OS: Manjaro Gnome (server), and Android 9 (Smartphone)

**Additional context**

**Comment by smashah** [comment] 2021-06-13 12:22
This is not a bug. It is closing the browser window because it is not able to load the wa web page so the process closes so you can try again.

If you do not want the browser/process to close then set `killProcessOnTimeout: false`. The error will still happen though. It is due to networking issues.

**Closed by smashah** 2021-06-13 12:22 UTC
