### ISSUE TITLE
Error: Evaluation failed: n

### ISSUE THREAD

**Issue by dngda** [open-wa/wa-automate-nodejs#1347] opened 2021-02-14 11:56 UTC
**Describe the bug**
Got Error: Evaluation failed: n when trying to send sticker using image

> Error: Evaluation failed: n
    at ExecutionContext._evaluateInternal (E:\node\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (E:\node\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)

**Steps to Reproduce**
So the goal is to create sticker using image sent to the bot

```javascript
///onMessage handling
const encryptMedia = isQuotedImage ? quotedMsg : message
const _mimetype = isQuotedImage ? quotedMsg.mimetype : mimetype
const mediaData = await decryptMedia(encryptMedia)
const imageBase64 = `data:${_mimetype};base64,${mediaData.toString('base64')}`
client.sendImageAsSticker(from, imageBase64, stickerMetadata)
    .then(() => {
        client.sendText(from, 'Here\'s your sticker')
        console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
    }).catch(err => {
        console.log(err)
        client.sendText(from, 'Maaf, ada yang error!')
    })
```

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        sessionId: 'session',
        headless: true,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    })
```

**Expected behavior**
I have no idea, maybe the decryptMedia function?
I can't send other normal image too

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: "2.2104.9",
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.4.1',
  BROWSER_VERSION: 'HeadlessChrome/90.0.4403.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: 'Windows 10'

**Additional context**
No idea

**Comment by smashah** [comment] 2021-02-14 13:01
Can you log the result of each line to pinpoint when exactly this error occurs, please? Also, does this happen on all media? Can you provide a sample of an image where this happens. Does it still happen when you restart the session? Might need to see the rest of your code to recreate this issue

**Comment by dngda** [comment] 2021-02-14 14:01
Well, when I'm trying to make the error again, it seems to be working fine after many sessions restart. Lmao.
Will get back to you with more details if the same error occurs. Thanks

**Comment by smashah** [comment] 2021-02-14 14:29
@dngda when there's a new WA update, like `2.2104.9`, things get messed up temporarily over a few sessions. The best thing is to do is restart a few times to make sure the issue is reproducible before you report it (mainly to save you the hassle of filling in the template lol - which you did a great job with and is much appreciated).

I'm going to close this issue for now but please report back if it happens again and any further context/reproduction steps.

Thanks!

**Closed by smashah** 2021-02-14 14:29 UTC
Labels: Template Champion of the Day 👑
