### ISSUE TITLE
CLI is not working

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#3117] opened 2023-05-12 11:30 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

I am using the follow command to start an CLI and use it in an **Ubuntu 22.04** server:

`docker run -p 8080:8080 --init openwa/wa-automate -p 8080 -k '<key>' --keep-alive -w <webhook_url> -l <license> --api-host '<host>'`

Immediately, when I run that command, I receives this error:

```
class Collection extends collection_1.default {
                                      ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate-socket-client/dist/Collector.js:37:39)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate-socket-client/dist/MessageCollector.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)

Node.js v18.8.0
```

### Expected Behavior

This should allow me to scan the QR code and thus authenticate Whatsapp

### Steps To Reproduce

1. In an Ubuntu 22.04 server (4GB RAM/25 GB DISK)
2. Run this command: `docker run -p 8080:8080 --init openwa/wa-automate -p 8080 -k '<key>' --keep-alive -w <webhook_url> -l <license> --api-host '<host>'`

### DEBUG INFO

```markdown
The app doesn't even start
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Node: v18.8.0
- npm: 8.19.1
```

### Screenshots/Logs

![image](https://github.com/open-wa/wa-automate-nodejs/assets/49699162/33fe704e-c149-4b15-abc5-848550c715cd)

**Comment by danilocodes** [comment] 2023-05-12 15:15
I can confirm this same error happens using my own code

**Comment by edgaru** [comment] 2023-05-15 19:45
Same error.

**Comment by edgaru** [comment] 2023-05-16 15:48
Hello, any update on this issue? it does not allow to use the library.

**Comment by danilocodes** [comment] 2023-05-16 18:20
I tried to reproduce in a new project using the example in README.md and everything seems to be fine, but in my main project it won't even start.
I'm using typescript, could that be the issue?

**Comment by edgaru** [comment] 2023-05-16 18:47
No I am using it without typescript and I got the error.

**Comment by danilocodes** [comment] 2023-05-17 21:53
Got my session back online by removing package-lock.json and node_modules, doing a clean install.

**Comment by smashah** [comment] 2023-05-20 22:09
should be fixed now . silly discord issue

**Closed by smashah** 2023-05-20 22:09 UTC
