### ISSUE TITLE
LOOP STARTING

### ISSUE THREAD

**Issue by alvaroespinola** [open-wa/wa-automate-nodejs#2128] opened 2021-09-15 00:47 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

  '2.2136.8'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.20.8'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/93.0.4577.0'   
✖ Session data json file is corrupted. Please reauthenticate.
✓ Browser Launched
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2136.8'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.20.8'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/93.0.4577.0'                                                         │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1631665760560                                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
✓ Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2136.8%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.20.8%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/93.0.4577.0%22,%0A%20%20%22START_TS%22:%201631665760560%0A%7D&environment=-%20OS:%20Windows%2010%0A-%20Node:%2016.7.0%0A-%20npm:%20%0A
✖ Session data most likely expired due to manual host account logout. Please re-authenticate this session.

                                    ____/\\\\\\\\\\__________/\\\\\_______/\\\\\\\\\\\\\____/\\\\\\\\\\\\\\\__/\

### Expected Behavior

STARTUP LOOP

### Steps To Reproduce

npx @open-wa/wa-automate -p 8080 -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

Windows 10

### Mode

EASY API/CLI

### create() code

```markdown
npx @open-wa/wa-automate -p 8080 -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2136.8",
  "WA_AUTOMATE_VERSION": "4.20.8",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1631665973103
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.7.0
- npm: 7.19.0
```

### Screenshots

npx @open-wa/wa-automate -p 8080 -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

### Anything else?

npx @open-wa/wa-automate -p 8080 -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

**Comment by dogcalas** [comment] 2021-09-15 01:05
Duplicate of #2126

**Comment by manojsitapara** [comment] 2021-09-15 02:24
Same issue for me as well, just now this issue has been started till yesterday it was working fine

**Comment by smashah** [comment] 2021-09-15 02:33
Hi all, I'm looking into this. Please share your WA_VERSION, I'm getting `2.2136.9`

**Comment by manojsitapara** [comment] 2021-09-15 02:38
@smashah it is same WA_VERSION which you have

```
- Debug info: {
"WA_VERSION": "2.2136.9",
"PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
"WA_AUTOMATE_VERSION": "4.20.8",
"BROWSER_VERSION": "HeadlessChrome/93.0.4577.82",
"OS": "Linux 5.8",
"START_TS": 1631673447025
}
```

**Comment by smashah** [comment] 2021-09-15 03:25
track #2126 


Fix deployed. please try v4.21.0

**Closed by smashah** 2021-09-15 03:25 UTC
