### ISSUE TITLE
Deleting a single message delete all messages on chat

### ISSUE THREAD

**Issue by weverkley** [open-wa/wa-automate-nodejs#406] opened 2020-05-06 23:33 UTC
**Describe the bug**
When i try to delete a single message in a chat the system fires an error and instead of deleting that message it deletes everything in the chat.

**Steps to Reproduce**
1. call await client.deleteMessage(contactId, messageId, false)

**create() code**
This is the code you use to create the client. e.g
```javascript
create('session', {
  headless: true,
  autoRefresh: true,
  args: [
    '--proxy-server="direct://"',
    '--proxy-bypass-list=*'
  ]
}).then(client => start(client));
```

**Expected behavior**
Only a single message to be deleted.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2017.6',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.9',
  BROWSER_VERSION: 'HeadlessChrome/81.0.4044.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Additional context**

Scheenshot of the error [image](https://prnt.sc/sc9743)

**Comment by smashah** [comment] 2020-05-07 00:26
Needs more details on how to reproduce. Does this happen on every chat you try to delete a message from? Does it happen using any WhatsApp host number? Etc.

**Comment by weverkley** [comment] 2020-05-07 02:43
> Needs more details on how to reproduce. Does this happen on every chat you try to delete a message from? Does it happen using any WhatsApp host number? Etc.

Yes for both answers

**Comment by smashah** [comment] 2020-05-07 02:53
When I say it needs more details, it doesn't mean only the subsequent questions. Does it happen without the proxy? I cannot reproduce with the limited information here. Needs more context and screenshots of the chats where this is happening. Please add all the `start` code also.

**Comment by smashah** [comment] 2020-05-08 19:33
@weverkley I've added a test in the demo that should delete any message with the text 'DELETE'. It is tested to be working perfectly and as expected, try it out:

https://github.com/open-wa/wa-automate-nodejs/commit/3e0c4bc0c30ab03d8962264d9bd236088434c561

I'm going to close this for now until you can provide some reproducible instructions.

Thanks

**Closed by smashah** 2020-05-08 19:33 UTC
