### ISSUE TITLE
Can't start client with multidevice beta

### ISSUE THREAD

**Issue by WolfDWyc** [open-wa/wa-automate-nodejs#1923] opened 2021-07-20 16:44 UTC
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When the new multidevice beta is enabled, I can't start the client and I get this error:
```javascript
✖ QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:273
                    throw new Error('QR Timeout');
                          ^

Error: QR Timeout
    at node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:273:27
    at Generator.next (<anonymous>)
    at fulfilled (node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
 ```

### Expected Behavior

The client should start normally.

### Steps To Reproduce

1. Environment: Windows 10
2. On android, join google play's whatsapp beta. Now click the 3 dots on whatsapp's main screen, and click "Linked devices". From there, click the "Multi-device beta" tab, and click the "JOIN BETA" button in the bottom.
3. Run: 
```javascript
wa.create().then(client => start(client));
```
and try authenticating.
4. Wait until it times out.

 **INFO:**
I tried increasing the QR timeout to 120 seconds and it still didn't work. 

### Mode

EASY API/CLI

### create() code
```javascript
wa.create().then(client => start(client));
```

Or:
```javascript
wa.create({qrTimeout:120}).then(client => start(client));
```

### DEBUG INFO

```markdown
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2126.12'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.11.1'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/92.0.4512.0'                                                         │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1626799229301                                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Environment

```markdown
- OS: Windows 10 
- Node: 16.5.0
- npm: 7.20.0
```

**Comment by tinyCoder32** [comment] 2021-07-20 23:35
Confirmed.

**Comment by smashah** [comment] 2021-07-20 23:37
I suggest keeping multidevice on only for already authenticated sessions until I'm able to debug +fix this

**Comment by WolfDWyc** [comment] 2021-07-21 00:55
> I suggest keeping multidevice on only for already authenticated sessions until I'm able to debug +fix this

I just tested this and it doesn't work (the client stops working without showing any error). This is probably because joining the beta logs out from all whatsapp web devices.

**Comment by tiagomatrixd** [comment] 2021-07-21 05:52
here I tested it and it has the same problem.
after reading the qr it generates a new one to be able to authenticate

**Comment by smashah** [comment] 2021-07-21 14:22
Ok well till I get a hold of multidevice I suggest that no one use it with open-wa.

**Comment by smashah** [comment] 2021-07-23 18:06
In version 4.12.0, the library will not crash when you set `multiDevice: true` in your configs.

However, reauthenticating a closed session is still not implemented. The solution, for now, is to set a `datadir` for puppeteer but in my opinion, it is a completely substandard fix because of all the trash it generates in your local filesystems. 

I will continue working on this but as it is a luxury, not a necessity, I will be prioritizing other work instead.

For now, I suggest nobody use the multi-device beta. After all, it has bugs and limitations of its own anyways.

Closing. I will reopen when I implement the solution to this. Thanks

**Closed** 2021-07-23 18:07 UTC
